global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pfelink-monolith'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8081'] # Use 'host.docker.internal:8081' if running app outside Docker

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

